import { runGraph } from "./langgraph/basic-examples/0-text-transformer";
import { runCaluclator } from "./langgraph/basic-examples/1-calculator-ops";
import { runTriageRouter } from "./langgraph/basic-examples/2-triage-router";
import { runValidationGraph } from "./langgraph/basic-examples/3-state-accumulation";
import { runWeatherAgent } from "./langchain-agents/examples/0-weather-app-tool";
import { runWeatherAgentWorkflow } from "./langgraph/architecture-examples/0-weather-app-custom-graph";
import { runNodeStyleMiddleware } from "./langchain-agents/examples/1-middlewares-node-hooks";
import { runWrapStyleMiddleware } from "./langchain-agents/examples/2-middlewares-wrap-hooks";
import { runWeatherAgentWorkflowWithMiddlewares } from "./langgraph/architecture-examples/1-middleware-custom-graph";
import { runSeriesGenerator } from "./langgraph/architecture-examples/2-middleware-custom-graph";
import { runAgentWithThreadId } from "./langchain-agents/examples/3-short-term-memory";
import { runWorkflowWithShortTermMemory } from "./langgraph/architecture-examples/3-short-term-memory-intro";
import { runInterruptBefore } from "./langgraph/architecture-examples/6-interrupt-before";
import { runWeatherAgentWorkflowWithInterruptCommand } from "./langgraph/architecture-examples/7-interrupt-command";
import { runInterruptCommand2 } from "./langgraph/architecture-examples/8-interrupt-command-2";

// runGraph();
// runCaluclator();
// runTriageRouter();
// runValidationGraph();
// runWeatherAgent();
// runWeatherAgentWorkflow();
// runNodeStyleMiddleware();
// runWrapStyleMiddleware();
// runWeatherAgentWorkflowWithMiddlewares();
// runSeriesGenerator();
// runAgentWithThreadId();
// runWorkflowWithShortTermMemory();
// runInterruptBefore();
// runWeatherAgentWorkflowWithInterruptCommand();
runInterruptCommand2();